# ***NumPy Comprehensive Tutorial***




## Create a NumPy ndarray Object

Different dimensions of array

In [ ]:
import numpy as np
arr1= np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
#this is example of 1d array

print("\n")

#this is example of 2d array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

#this is 3d array
print("\n")
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr3)

#printing number of dimensions using function

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)




[1 2 3 4 5]
<class 'numpy.ndarray'>


[[1 2 3]
 [4 5 6]]


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3


verifying dimension of array

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print("the dimension=",arr.ndim)

[[[[[1 2 3 4 5]]]]]
the dimension= 5


#accessing the index of array elements

In [ ]:
arr=np.array([1,2,3,4,5,6])

print(arr[1])


2


10


getting the index of 3 and 5 element and adding them

In [ ]:
print("\n")
print(arr[3]+arr[5])



10


accessing 2d arrays

In [ ]:
import numpy as np
arr= np.array([[1,2,3,4,5],[6,7,8,9,10]])

print("2nd element first row",arr[0,1])

2nd element first row 2


# NumPy Array Slicing

##**How to slice array=**
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

**Note: The result includes the start index, but excludes the end index.**

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

print(arr[0:5])

[1 2 3 4 5]


Example
Slice elements from index 4 to the end of the array:

In [ ]:
import numpy as np
arr= np.array([1,2,3,4,5,6])
print(arr[4:])

[5 6]


negative slicing

In [ ]:
arr= np.array([1,2,3,4,5,6])
print(arr[-3:-1])

[4 5]


slicing using *step*

In [ ]:
arr= np.array([1,2,3,4,5,6])
print(arr[0:6:2])
print("\n")
print(arr[::2])

[1 3 5]


[1 3 5]


#Data types in python and numpy

to know datatype of elements

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])

print(arr.dtype)

int64


how to convert datatype

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6],dtype='i4')
print (arr.dtype)


int32


In [ ]:
arr=np.array([1.1,2.2,3.3,4.4])

newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


#COPY AND VIEW

In [ ]:
import numpy as np
arr =np.array([1,2,3,4,5,6])
newarr=arr.copy()
arr[0]=42
print(arr)
print(newarr)
#this is example of copy

[42  2  3  4  5  6]
[1 2 3 4 5 6]


In [ ]:
arr =np.array([1,2,3,4,5,6])
newarr=arr.view()
arr[0]=42
print(arr)
print(newarr)
#this example of view

[42  2  3  4  5  6]
[42  2  3  4  5  6]


#Numpy array shaping

In [ ]:
import numpy as np
arr=np.array ([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)

(2, 5)


this **ndmin** is used to force array of respected size ---------⬇️

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)


[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


##reshaping array in numy

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


##iterating through array

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

for i in arr:
  print(i);

1
2
3
4
5
6


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

for i in arr:
  print(i);

[1 2 3]
[4 5 6]


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

for i in arr:
  for j in i:
    print(j);

1
2
3
4
5
6


#using nditer

**why nditer() is used in numpy**


why nditer is used in numpy
np.nditer() is an efficient multidimensional iterator object in NumPy designed to iterate over array elements sequentially.

While Python's standard for loops allow you to iterate over arrays, nditer() provides several key advantages:

Handles Arbitrary Dimensions Effortlessly: In standard Python, iterating down to every scalar element in an N-dimensional array requires nesting N separate for loops. np.nditer() flattens this into a single loop regardless of the array's shape or dimension count.

C-Level Performance: np.nditer() is implemented in C, making loop execution significantly faster than standard nested Python for loops.

Flexible Data Type Casting: By enabling buffering (e.g., flags=['buffered']), you can cast elements to a different data type on the fly during iteration using the op_dtypes argument without altering the original array in memory.

Broadcasting Support: It allows simultaneous iteration over multiple arrays that follow NumPy's broadcasting rules without manually allocating memory or reshaping arrays.

Advanced Memory Layout Control: You can explicitly choose the order in which elements are visited (such as C-style contiguous row-major order or Fortran-style column-major order) regardless of how the array is stored in memory.





In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])



1
2
3
4
5
6
7
8


## Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


# NumPy Joining Array
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [ ]:
import numpy as np
arr1 =np.array([1,2,3,4,5,6])
arr2 =np.array([7,8,9,10])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## joining 2d array

In [ ]:
import numpy as np
arr1 =np.array([[1,2,3,4],[1,2,3,4]])
arr2= np.array([[4,3,2,1],[4,3,2,1]])
arr =np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 4 4 3 2 1]
 [1 2 3 4 4 3 2 1]]


## using stack function to join array


In [ ]:
import numpy as np
arr1 =np.array([1,2,3,4,5])
arr2 =np.array([1,2,3,4,5])
arr =np.stack((arr1,arr2),axis=1)
print(arr)

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


## stacking along rows

In [ ]:
import numpy as np
arr1 =np.array([1,2,3,4,5])
arr2 =np.array([1,2,3,4,5])
arr =np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 1 2 3 4 5]


## stacking across column

In [ ]:
import numpy as np
arr1 =np.array([1,2,3,4,5])
arr2 =np.array([1,2,3,4,5])
arr =np.vstack((arr1,arr2))
print(arr)

[[1 2 3 4 5]
 [1 2 3 4 5]]


## stacking along height(depth)

In [ ]:
import numpy as np
arr1 =np.array([1,2,3,4,5])
arr2 =np.array([1,2,3,4,5])
arr =np.dstack((arr1,arr2))# d=depth
print(arr)

[[[1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]]]


# NumPy Comprehensive Tutorial

**Created by:** Shreyas Kumbhar
**GitHub:** [@Shreyask28](https://github.com/Shreyask28)  
**LinkedIn:** [shreyas-kumbhar](https://linkedin.com/in//shreyas-kumbhar-63715237a/)  
**Email:** kumbharshreyas7777@gmail.com  

---
*A step-by-step guide covering fundamental to advanced NumPy operations.*